ATTN_TO_SNDLEVEL 
AcceptEntityInput 
ActivateEntity 
AddAdmGroupCmdOverride 
AddAmbientSoundHook 
AddCommandListener 
AddCommandOverride 
AddFileToDownloadsTable 
AddGameLogHook 
AddMenuItem 
AddMultiTargetFilter 
AddNormalSoundHook 
AddServerTag 
AddTargetsToMenu 
AddTargetsToMenu2 
AddTempEntHook 
AddToForward 
AddToStringTable 
AddToTopMenu 
AddUserFlags 
AddVectors 
AdminInheritGroup 
ArcCosine 
ArcSine 
ArcTangent 
ArcTangent2 
AreClientCookiesCached 
AskPluginLoad2 
AssertEq 
AssertFalse 
AssertTrue 
AutoExecConfig 
BanClient 
BanIdentity 
BaseComm_IsClientGagged 
BaseComm_IsClientMuted 
BaseComm_OnClientGag 
BaseComm_OnClientMute 
BaseComm_SetClientGag 
BaseComm_SetClientMute 
BfGetNumBytesLeft 
BfReadAngle 
BfReadAngles 
BfReadBool 
BfReadByte 
BfReadChar 
BfReadCoord 
BfReadEntity 
BfReadFloat 
BfReadNum 
BfReadShort 
BfReadString 
BfReadVecCoord 
BfReadVecNormal 
BfReadWord 
BfWriteAngle 
BfWriteAngles 
BfWriteBool 
BfWriteByte 
BfWriteChar 
BfWriteCoord 
BfWriteEntity 
BfWriteFloat 
BfWriteNum 
BfWriteShort 
BfWriteString 
BfWriteVecCoord 
BfWriteVecNormal 
BfWriteWord 
BindAdminIdentity 
BitToFlag 
BreakString 
BuildPath 
ByteCountToCells 
CS_AliasToWeaponID 
CS_DropWeapon 
CS_GetClientAssists 
CS_GetClientClanTag 
CS_GetClientContributionScore 
CS_GetMVPCount 
CS_GetTeamScore 
CS_GetTranslatedWeaponAlias 
CS_GetWeaponPrice 
CS_IsValidWeaponID 
CS_ItemDefIndexToID 
CS_OnBuyCommand 
CS_OnCSWeaponDrop 
CS_OnGetWeaponPrice 
CS_OnTerminateRound 
CS_RespawnPlayer 
CS_SetClientAssists 
CS_SetClientClanTag 
CS_SetClientContributionScore 
CS_SetMVPCount 
CS_SetTeamScore 
CS_SwitchTeam 
CS_TerminateRound 
CS_UpdateClientModel 
CS_WeaponIDToAlias 
CS_WeaponIDToItemDefIndex 
Call_Cancel 
Call_Finish 
Call_PushArray 
Call_PushArrayEx 
Call_PushCell 
Call_PushCellRef 
Call_PushFloat 
Call_PushFloatRef 
Call_PushNullString 
Call_PushNullVector 
Call_PushString 
Call_PushStringEx 
Call_StartForward 
Call_StartFunction 
CanAdminTarget 
CanMapChooserStartVote 
CanPanelDrawFlags 
CanTestFeatures 
CanUserTarget 
CancelClientMenu 
CancelCreatedEvent 
CancelMenu 
CancelVote 
ChangeClientTeam 
ChangeEdictState 
CharToLower 
CharToUpper 
CheckAccess 
CheckCommandAccess 
CheckVoteDelay 
ClearArray 
ClearSyncHud 
ClearTrie 
ClientCommand 
CloneArray 
CloneHandle 
CloseHandle 
CommandExists 
CompileRegex 
Cosine 
CreateAdmGroup 
CreateAdmin 
CreateArray 
CreateAuthMethod 
CreateConVar 
CreateDataPack 
CreateDataTimer 
CreateDialog 
CreateDirectory 
CreateEdict 
CreateEntityByName 
CreateEvent 
CreateFakeClient 
CreateForward 
CreateGlobalForward 
CreateHudSynchronizer 
CreateKeyValues 
CreateMenu 
CreateMenuEx 
CreateNative 
CreatePanel 
CreatePanelFromMenu 
CreateProfiler 
CreateStack 
CreateTimer 
CreateTopMenu 
CreateTrie 
CreateTrieSnapshot 
DegToRad 
DeleteFile 
DirExists 
DispatchKeyValue 
DispatchKeyValueFloat 
DispatchKeyValueVector 
DispatchSpawn 
DisplayAskConnectBox 
DisplayMenu 
DisplayMenuAtItem 
DisplayTopMenu 
DisplayTopMenuCategory 
DrawPanelItem 
DrawPanelText 
DumpAdminCache 
EmitAmbientGameSound 
EmitAmbientSound 
EmitGameSound 
EmitGameSoundToAll 
EmitGameSoundToClient 
EmitSentence 
EmitSound 
EmitSoundEntry 
EmitSoundToAll 
EmitSoundToClient 
EndMessage 
EndOfMapVoteEnabled 
EndPrepSDKCall 
EntIndexToEntRef 
EntRefToEntIndex 
EnterProfilingEvent 
EquipPlayerWeapon 
ExplodeString 
Exponential 
ExtendMapTimeLimit 
ExtinguishEntity 
FadeClientVolume 
FakeClientCommand 
FakeClientCommandEx 
FakeClientCommandKeyValues 
FileExists 
FilePosition 
FileSeek 
FileSize 
FileToKeyValues 
FindAdmGroup 
FindAdminByIdentity 
FindCharInString 
FindClientCookie 
FindCommandLineParam 
FindConVar 
FindDataMapInfo 
FindEntityByClassname 
FindFirstConCommand 
FindFlagByChar 
FindFlagByName 
FindFlagChar 
FindMap 
FindNextConCommand 
FindPluginByFile 
FindPluginByNumber 
FindSendPropInfo 
FindStringInArray 
FindStringIndex 
FindStringTable 
FindTarget 
FindTeamByName 
FindTopMenuCategory 
FindValueInArray 
FireEntityOutput 
FireEvent 
FlagArrayToBits 
FlagBitArrayToBits 
FlagBitsToArray 
FlagBitsToBitArray 
FlagToBit 
FloatAbs 
FloatAdd 
FloatCompare 
FloatDiv 
FloatFraction 
FloatMul 
FloatSub 
FloatToString 
FlushFile 
ForceChangeLevel 
ForcePlayerSuicide 
Format 
FormatActivitySource 
FormatEx 
FormatNativeString 
FormatTime 
FormatUserLogText 
GameConfGetAddress 
GameConfGetKeyValue 
GameConfGetOffset 
GameRules_GetProp 
GameRules_GetPropEnt 
GameRules_GetPropFloat 
GameRules_GetPropString 
GameRules_GetPropVector 
GameRules_GetRoundState 
GameRules_SetProp 
GameRules_SetPropEnt 
GameRules_SetPropFloat 
GameRules_SetPropString 
GameRules_SetPropVector 
GeoipCode2 
GeoipCode3 
GeoipCountry 
GetAdmGroupAddFlag 
GetAdmGroupAddFlags 
GetAdmGroupCmdOverride 
GetAdmGroupImmuneCount 
GetAdmGroupImmuneFrom 
GetAdmGroupImmunityLevel 
GetAdminFlag 
GetAdminFlags 
GetAdminGroup 
GetAdminGroupCount 
GetAdminImmunityLevel 
GetAdminPassword 
GetAdminTopMenu 
GetAdminUsername 
GetAngleVectors 
GetArrayArray 
GetArrayBlockSize 
GetArrayCell 
GetArraySize 
GetArrayString 
GetCharBytes 
GetClientAbsAngles 
GetClientAbsOrigin 
GetClientAimTarget 
GetClientArmor 
GetClientAuthId 
GetClientAvgChoke 
GetClientAvgData 
GetClientAvgLatency 
GetClientAvgLoss 
GetClientAvgPackets 
GetClientButtons 
GetClientCookie 
GetClientCookieTime 
GetClientCount 
GetClientDataRate 
GetClientDeaths 
GetClientEyeAngles 
GetClientEyePosition 
GetClientFrags 
GetClientFromSerial 
GetClientHealth 
GetClientIP 
GetClientInfo 
GetClientLanguage 
GetClientLatency 
GetClientListeningFlags 
GetClientMaxs 
GetClientMenu 
GetClientMins 
GetClientModel 
GetClientName 
GetClientOfUserId 
GetClientSerial 
GetClientTeam 
GetClientTime 
GetClientUserId 
GetClientWeapon 
GetClientsInRange 
GetCmdArg 
GetCmdArgString 
GetCmdArgs 
GetCmdReplySource 
GetCommandFlags 
GetCommandIterator 
GetCommandLine 
GetCommandLineParam 
GetCommandLineParamFloat 
GetCommandLineParamInt 
GetCommandOverride 
GetConVarBool 
GetConVarBounds 
GetConVarDefault 
GetConVarFlags 
GetConVarFloat 
GetConVarInt 
GetConVarName 
GetConVarString 
GetCookieAccess 
GetCookieIterator 
GetCurrentMap 
GetDistGainFromSoundLevel 
GetEdictClassname 
GetEdictFlags 
GetEngineTime 
GetEngineVersion 
GetEntData 
GetEntDataArray 
GetEntDataEnt2 
GetEntDataFloat 
GetEntDataString 
GetEntDataVector 
GetEntProp 
GetEntPropArraySize 
GetEntPropEnt 
GetEntPropFloat 
GetEntPropString 
GetEntPropVector 
GetEntSendPropOffs 
GetEntityAddress 
GetEntityClassname 
GetEntityCount 
GetEntityFlags 
GetEntityGravity 
GetEntityMoveType 
GetEntityNetClass 
GetEntityRenderColor 
GetEntityRenderFx 
GetEntityRenderMode 
GetEventBool 
GetEventFloat 
GetEventInt 
GetEventName 
GetEventString 
GetExcludeMapList 
GetExtensionFileStatus 
GetFeatureStatus 
GetFileTime 
GetForwardFunctionCount 
GetFunctionByName 
GetGameDescription 
GetGameFolderName 
GetGameFrameTime 
GetGameSoundParams 
GetGameTickCount 
GetGameTime 
GetLanguageByCode 
GetLanguageByName 
GetLanguageCount 
GetLanguageInfo 
GetListenOverride 
GetMapDisplayName 
GetMapHistory 
GetMapHistorySize 
GetMapTimeLeft 
GetMapTimeLimit 
GetMaxClients 
GetMaxEntities 
GetMaxHumanPlayers 
GetMaxPageItems 
GetMenuExitBackButton 
GetMenuExitButton 
GetMenuItem 
GetMenuItemCount 
GetMenuOptionFlags 
GetMenuPagination 
GetMenuSelectionPosition 
GetMenuStyle 
GetMenuStyleHandle 
GetMenuTitle 
GetMenuVoteInfo 
GetMyHandle 
GetNativeArray 
GetNativeCell 
GetNativeCellRef 
GetNativeFunction 
GetNativeString 
GetNativeStringLength 
GetNextMap 
GetNominatedMapList 
GetNumStringTables 
GetPackPosition 
GetPanelCurrentKey 
GetPanelStyle 
GetPanelTextRemaining 
GetPlayerDecalFile 
GetPlayerJingleFile 
GetPlayerResourceEntity 
GetPlayerWeaponSlot 
GetPluginFilename 
GetPluginInfo 
GetPluginIterator 
GetPluginStatus 
GetProfilerTime 
GetRandomFloat 
GetRandomInt 
GetRegexSubString 
GetServerAuthId 
GetServerLanguage 
GetServerNetStats 
GetServerSteamAccountId 
GetStackBlockSize 
GetSteamAccountID 
GetStringTableData 
GetStringTableDataLength 
GetStringTableMaxStrings 
GetStringTableName 
GetStringTableNumStrings 
GetSysTickCount 
GetTeamClientCount 
GetTeamCount 
GetTeamEntity 
GetTeamName 
GetTeamScore 
GetTickInterval 
GetTickedTime 
GetTime 
GetTopMenuInfoString 
GetTopMenuObjName 
GetTrieArray 
GetTrieSize 
GetTrieSnapshotKey 
GetTrieString 
GetTrieValue 
GetURandomFloat 
GetURandomInt 
GetUserAdmin 
GetUserFlagBits 
GetUserMessageId 
GetUserMessageName 
GetUserMessageType 
GetVectorAngles 
GetVectorCrossProduct 
GetVectorDistance 
GetVectorDotProduct 
GetVectorLength 
GetVectorVectors 
GivePlayerAmmo 
GivePlayerItem 
HasEndOfMapVoteFinished 
HasEntProp 
HookConVarChange 
HookEntityOutput 
HookEvent 
HookEventEx 
HookSingleEntityOutput 
HookUserMessage 
IgniteEntity 
ImplodeStrings 
InactivateClient 
InitiateMapChooserVote 
InsertMenuItem 
InsertServerCommand 
IntToString 
InternalShowMenu 
IsCharAlpha 
IsCharLower 
IsCharMB 
IsCharNumeric 
IsCharSpace 
IsCharUpper 
IsChatTrigger 
IsClientAuthorized 
IsClientConnected 
IsClientInGame 
IsClientInKickQueue 
IsClientInVotePool 
IsClientMuted 
IsClientObserver 
IsClientReplay 
IsClientSourceTV 
IsClientTimingOut 
IsDecalPrecached 
IsDedicatedServer 
IsEndOfFile 
IsEntNetworkable 
IsFakeClient 
IsGenericPrecached 
IsMapValid 
IsModelPrecached 
IsNativeParamNullString 
IsNativeParamNullVector 
IsNewVoteAllowed 
IsNullString 
IsNullVector 
IsPackReadable 
IsPlayerAlive 
IsPluginDebugging 
IsProfilingActive 
IsServerProcessing 
IsSoundPrecached 
IsStackEmpty 
IsTranslatedForLanguage 
IsValidConVarChar 
IsValidEdict 
IsValidEntity 
IsVoteInProgress 
KeyValuesToFile 
KickClient 
KickClientEx 
KillTimer 
KvCopySubkeys 
KvDeleteKey 
KvDeleteThis 
KvFindKeyById 
KvGetColor 
KvGetDataType 
KvGetFloat 
KvGetNameSymbol 
KvGetNum 
KvGetSectionName 
KvGetSectionSymbol 
KvGetString 
KvGetUInt64 
KvGetVector 
KvGoBack 
KvGotoFirstSubKey 
KvGotoNextKey 
KvJumpToKey 
KvJumpToKeySymbol 
KvNodesInStack 
KvRewind 
KvSavePosition 
KvSetColor 
KvSetEscapeSequences 
KvSetFloat 
KvSetNum 
KvSetSectionName 
KvSetString 
KvSetUInt64 
KvSetVector 
LeaveProfilingEvent 
LibraryExists 
LoadFromAddress 
LoadGameConfigFile 
LoadTopMenuConfig 
LoadTranslations 
LockStringTables 
LogAction 
LogError 
LogMessage 
LogToFile 
LogToFileEx 
LogToGame 
LogToOpenFile 
LogToOpenFileEx 
Logarithm 
MakeCompatEntRef 
MakeVectorFromPoints 
MarkNativeAsOptional 
MatchRegex 
MorePlugins 
NegateVector 
NominateMap 
NormalizeVector 
NotifyPostAdminCheck 
OnAdminMenuCreated 
OnAdminMenuReady 
OnAllPluginsLoaded 
OnAutoConfigsBuffered 
OnBanClient 
OnBanIdentity 
OnClientAuthorized 
OnClientCommand 
OnClientCommandKeyValues 
OnClientCommandKeyValues_Post 
OnClientConnect 
OnClientConnected 
OnClientCookiesCached 
OnClientDisconnect 
OnClientDisconnect_Post 
OnClientFloodCheck 
OnClientFloodResult 
OnClientPostAdminCheck 
OnClientPostAdminFilter 
OnClientPreAdminCheck 
OnClientPutInServer 
OnClientSayCommand 
OnClientSayCommand_Post 
OnClientSettingsChanged 
OnConfigsExecuted 
OnEntityCreated 
OnEntityDestroyed 
OnFileReceive 
OnFileSend 
OnGameFrame 
OnGetGameDescription 
OnLevelInit 
OnLibraryAdded 
OnLibraryRemoved 
OnLogAction 
OnMapEnd 
OnMapStart 
OnMapTimeLeftChanged 
OnMapVoteStarted 
OnNominationRemoved 
OnPlayerRunCmd 
OnPlayerRunCmdPost 
OnPluginEnd 
OnPluginPauseChange 
OnPluginStart 
OnRebuildAdminCache 
OnRemoveBan 
OpenDirectory 
OpenFile 
PbAddAngle 
PbAddBool 
PbAddColor 
PbAddFloat 
PbAddInt 
PbAddMessage 
PbAddString 
PbAddVector 
PbAddVector2D 
PbGetRepeatedFieldCount 
PbReadAngle 
PbReadBool 
PbReadColor 
PbReadFloat 
PbReadInt 
PbReadMessage 
PbReadRepeatedMessage 
PbReadString 
PbReadVector 
PbReadVector2D 
PbRemoveRepeatedFieldValue 
PbSetAngle 
PbSetBool 
PbSetColor 
PbSetFloat 
PbSetInt 
PbSetString 
PbSetVector 
PbSetVector2D 
PopStack 
PopStackArray 
PopStackCell 
PopStackString 
Pow 
PrecacheDecal 
PrecacheGeneric 
PrecacheModel 
PrecacheScriptSound 
PrecacheSentenceFile 
PrecacheSound 
PrefetchSound 
PrepSDKCall_AddParameter 
PrepSDKCall_SetAddress 
PrepSDKCall_SetFromConf 
PrepSDKCall_SetReturnInfo 
PrepSDKCall_SetSignature 
PrepSDKCall_SetVirtual 
PrintCenterText 
PrintCenterTextAll 
PrintHintText 
PrintHintTextToAll 
PrintToChat 
PrintToChatAll 
PrintToConsole 
PrintToConsoleAll 
PrintToServer 
ProcessTargetString 
PushArrayArray 
PushArrayCell 
PushArrayString 
PushStackArray 
PushStackCell 
PushStackString 
QueryClientConVar 
RadToDeg 
ReadCommandIterator 
ReadCookieIterator 
ReadDirEntry 
ReadFile 
ReadFileCell 
ReadFileLine 
ReadFileString 
ReadFlagString 
ReadMapList 
ReadPackCell 
ReadPackFloat 
ReadPackFunction 
ReadPackString 
ReadPlugin 
ReadStringTable 
ReconnectClient 
RedisplayAdminMenu 
RedrawClientVoteMenu 
RedrawMenuItem 
RegAdminCmd 
RegClientCookie 
RegConsoleCmd 
RegPluginLibrary 
RegServerCmd 
RegisterAuthIdentType 
RemoveAdmin 
RemoveAllFromForward 
RemoveAllMenuItems 
RemoveAmbientSoundHook 
RemoveBan 
RemoveCommandListener 
RemoveDir 
RemoveEdict 
RemoveEntity 
RemoveFromArray 
RemoveFromForward 
RemoveFromTopMenu 
RemoveFromTrie 
RemoveGameLogHook 
RemoveMenuItem 
RemoveMultiTargetFilter 
RemoveNominationByMap 
RemoveNominationByOwner 
RemoveNormalSoundHook 
RemovePlayerItem 
RemoveServerTag 
RemoveTempEntHook 
RemoveUserFlags 
RenameFile 
ReplaceString 
ReplaceStringEx 
ReplyToCommand 
ReplyToTargetError 
RequestFrame 
RequireFeature 
ResetConVar 
ResetPack 
ResizeArray 
RoundFloat 
RoundToCeil 
RoundToFloor 
RoundToNearest 
RoundToZero 
RunAdminCacheChecks 
SDKCall 
SDKHook 
SDKHookEx 
SDKHooks_DropWeapon 
SDKHooks_TakeDamage 
SDKUnhook 
SMC_CreateParser 
SMC_GetErrorString 
SMC_ParseFile 
SMC_SetParseEnd 
SMC_SetParseStart 
SMC_SetRawLine 
SMC_SetReaders 
SQL_AddQuery 
SQL_BindParamFloat 
SQL_BindParamInt 
SQL_BindParamString 
SQL_CheckConfig 
SQL_Connect 
SQL_ConnectCustom 
SQL_CreateTransaction 
SQL_DefConnect 
SQL_EscapeString 
SQL_Execute 
SQL_ExecuteTransaction 
SQL_FastQuery 
SQL_FetchFloat 
SQL_FetchInt 
SQL_FetchMoreResults 
SQL_FetchRow 
SQL_FetchSize 
SQL_FetchString 
SQL_FieldNameToNum 
SQL_FieldNumToName 
SQL_FormatQuery 
SQL_GetAffectedRows 
SQL_GetDriver 
SQL_GetDriverIdent 
SQL_GetDriverProduct 
SQL_GetError 
SQL_GetFieldCount 
SQL_GetInsertId 
SQL_GetRowCount 
SQL_HasResultSet 
SQL_IsFieldNull 
SQL_IsSameConnection 
SQL_LockDatabase 
SQL_MoreRows 
SQL_PrepareQuery 
SQL_Query 
SQL_QuoteString 
SQL_ReadDriver 
SQL_Rewind 
SQL_SetCharset 
SQL_TConnect 
SQL_TQuery 
SQL_UnlockDatabase 
SQLite_UseDatabase 
ScaleVector 
SendConVarValue 
SendPanelToClient 
ServerCommand 
ServerCommandEx 
ServerExecute 
SetAdmGroupAddFlag 
SetAdmGroupImmuneFrom 
SetAdmGroupImmunityLevel 
SetAdminFlag 
SetAdminImmunityLevel 
SetAdminPassword 
SetArrayArray 
SetArrayCell 
SetArrayString 
SetAuthIdCookie 
SetClientCookie 
SetClientInfo 
SetClientLanguage 
SetClientListeningFlags 
SetClientName 
SetClientViewEntity 
SetCmdReplySource 
SetCommandFlags 
SetConVarBool 
SetConVarBounds 
SetConVarFlags 
SetConVarFloat 
SetConVarInt 
SetConVarString 
SetCookieMenuItem 
SetCookiePrefabMenu 
SetEdictFlags 
SetEntData 
SetEntDataArray 
SetEntDataEnt2 
SetEntDataFloat 
SetEntDataString 
SetEntDataVector 
SetEntProp 
SetEntPropEnt 
SetEntPropFloat 
SetEntPropString 
SetEntPropVector 
SetEntityFlags 
SetEntityGravity 
SetEntityHealth 
SetEntityModel 
SetEntityMoveType 
SetEntityRenderColor 
SetEntityRenderFx 
SetEntityRenderMode 
SetEventBool 
SetEventBroadcast 
SetEventFloat 
SetEventInt 
SetEventString 
SetFailState 
SetFakeClientConVar 
SetFilePermissions 
SetGlobalTransTarget 
SetHudTextParams 
SetHudTextParamsEx 
SetLightStyle 
SetListenOverride 
SetMapListCompatBind 
SetMenuExitBackButton 
SetMenuExitButton 
SetMenuNoVoteButton 
SetMenuOptionFlags 
SetMenuPagination 
SetMenuTitle 
SetNativeArray 
SetNativeCellRef 
SetNativeString 
SetNextMap 
SetPackPosition 
SetPanelCurrentKey 
SetPanelKeys 
SetPanelTitle 
SetRandomSeed 
SetStringTableData 
SetTeamScore 
SetTestContext 
SetTopMenuTitleCaching 
SetTrieArray 
SetTrieString 
SetTrieValue 
SetURandomSeed 
SetURandomSeedSimple 
SetUserAdmin 
SetUserFlagBits 
SetVariantBool 
SetVariantColor 
SetVariantEntity 
SetVariantFloat 
SetVariantInt 
SetVariantPosVector3D 
SetVariantString 
SetVariantVector3D 
SetVoteResultCallback 
ShiftArrayUp 
ShowActivity 
ShowActivity2 
ShowActivityEx 
ShowCookieMenu 
ShowHudText 
ShowMOTDPanel 
ShowSyncHudText 
ShowVGUIPanel 
SimpleRegexMatch 
Sine 
SlapPlayer 
SortADTArray 
SortADTArrayCustom 
SortCustom1D 
SortCustom2D 
SortFloats 
SortIntegers 
SortStrings 
SplitString 
SquareRoot 
StartMessage 
StartMessageAll 
StartMessageEx 
StartMessageOne 
StartPrepSDKCall 
StartProfiling 
StopProfiling 
StopSound 
StoreToAddress 
StrCat 
StrContains 
StrEqual 
StringToFloat 
StringToFloatEx 
StringToInt 
StringToIntEx 
StringToKeyValues 
StripQuotes 
SubtractVectors 
SwapArrayItems 
TE_IsValidProp 
TE_ReadFloat 
TE_ReadNum 
TE_ReadVector 
TE_Send 
TE_SendToAll 
TE_SendToAllInRange 
TE_SendToClient 
TE_SetupArmorRicochet 
TE_SetupBeamFollow 
TE_SetupBeamLaser 
TE_SetupBeamPoints 
TE_SetupBeamRing 
TE_SetupBeamRingPoint 
TE_SetupBloodSprite 
TE_SetupDust 
TE_SetupEnergySplash 
TE_SetupExplosion 
TE_SetupGlowSprite 
TE_SetupMetalSparks 
TE_SetupMuzzleFlash 
TE_SetupSmoke 
TE_SetupSparks 
TE_Start 
TE_WriteAngles 
TE_WriteEncodedEnt 
TE_WriteFloat 
TE_WriteFloatArray 
TE_WriteNum 
TE_WriteVector 
TF2_AddCondition 
TF2_CalcIsAttackCritical 
TF2_ChangeClientTeam 
TF2_DisguisePlayer 
TF2_GetClass 
TF2_GetClientTeam 
TF2_GetObjectMode 
TF2_GetObjectType 
TF2_GetPlayerClass 
TF2_IgnitePlayer 
TF2_IsHolidayActive 
TF2_IsPlayerInCondition 
TF2_IsPlayerInDuel 
TF2_MakeBleed 
TF2_OnConditionAdded 
TF2_OnConditionRemoved 
TF2_OnIsHolidayActive 
TF2_OnPlayerTeleport 
TF2_OnWaitingForPlayersEnd 
TF2_OnWaitingForPlayersStart 
TF2_RegeneratePlayer 
TF2_RemoveAllWeapons 
TF2_RemoveCondition 
TF2_RemovePlayerDisguise 
TF2_RemoveWeaponSlot 
TF2_RemoveWearable 
TF2_RespawnPlayer 
TF2_SetPlayerClass 
TF2_SetPlayerPowerPlay 
TF2_StunPlayer 
TR_DidHit 
TR_GetEndPosition 
TR_GetEntityIndex 
TR_GetFraction 
TR_GetHitGroup 
TR_GetPlaneNormal 
TR_GetPointContents 
TR_GetPointContentsEnt 
TR_PointOutsideWorld 
TR_TraceHull 
TR_TraceHullEx 
TR_TraceHullFilter 
TR_TraceHullFilterEx 
TR_TraceRay 
TR_TraceRayEx 
TR_TraceRayFilter 
TR_TraceRayFilterEx 
Tangent 
TeleportEntity 
ThrowError 
ThrowNativeError 
TranslationPhraseExists 
TrieSnapshotKeyBufferSize 
TrieSnapshotLength 
TriggerTimer 
TrimString 
UnhookConVarChange 
UnhookEntityOutput 
UnhookEvent 
UnhookSingleEntityOutput 
UnhookUserMessage 
UnsetCommandOverride 
UserMessageToBfRead 
UserMessageToBfWrite 
UserMessageToProtobuf 
VFormat 
VerifyCoreVersion 
VoteMenu 
VoteMenuToAll 
WriteFile 
WriteFileCell 
WriteFileLine 
WriteFileString 
WritePackCell 
WritePackFloat 
WritePackFunction 
WritePackString 
float 
strcmp 
strcopy 
strlen 
strncmp 
